@startuml 訪問者ドメインモデル図
skinparam componentStyle rectangle

' ログイン
[訪問者] --o [ログイン]
[ログイン] --o [ログアウト]

[ログイン] o-- [ユーザーID]
[ログイン] o-- [パスワード]
[ログイン] o-- [名前]
[ログイン] o-- [メールアドレス]
[ログイン] o-- [学校名]
[ログイン] o-- [所属名]
[ログイン] o-- [電話番号]
[ログイン] o-- [年齢]


@enduml