@startuml 図書館システムドメインモデル図
skinparam componentStyle rectangle

' 会員
' 会員番号、氏名、メールアドレス
[会員] o-- [会員番号]
[会員] o-- [氏名]
[会員] o-- [メールアドレス]

' 学生
' 貸出上限: 6冊
[学生] o-up- [会員]
[学生] o-- [雑誌貸出不可、（６冊まで貸し出し可能）]

' 教職員
' 貸出上限: 12冊
[教職員] o-up- [会員]
[教職員] o-- [雑誌貸出可能、１２冊まで貸し出し可能]


' 図書
' 管理番号、書名
[図書] o-- [管理番号]
[図書] o-- [書名]

' 書籍
[書籍] o-up- [図書]

' 雑誌
[雑誌] o-up- [図書]

' 貸出
' 貸出日、返却期限
[貸出] o-- [貸出日]
[貸出] o-- [返却期限日]
[貸出] o-- [会員]
[貸出] o-- [図書]

' 予約
' 予約日
[予約] o-- [予約日]
[予約] o-- [会員]
[予約] o-- [図書]

@enduml